SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MIN_SPEED = 50
PLAYER_MAX_SPEED = 750
PLAYER_ACCELERATION_RATE = 15
PLAYER_DECELERATION_RATE = -15
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 1000
PLAYER_SHOOT_COOLDOWN = 0.3
FPS = 60